### ISSUE TITLE
Report Yourself

### ISSUE THREAD

**Issue by Bruhh1234** [Crasher508/AdvancedReport#2]
Kannst du hinzufügen das spieler sich nicht selber reporten können
und eine benachrichtigung über einen neue report wäre nice vllt mit extra Perm.

Grüße Bruhh

**Comment by rac14** [comment]
Can you add that players can't report themselves
and a notification about a new report would be nice maybe with extra perm.

Greetings Bruhh

**Comment by Crasher508** [comment]
german:
1. Man kann sich nicht selbst reporten, da der eigene Name nicht im Dropdown erscheint
2. Es existiert bereits eine Discord Webhook Funktion

english:
1. You can not report yourself
2. Use Discord webhooks
--> issue redundant

**Comment by Crasher508** [comment]
Eine Nachricht an alle OnlinePlayer with perm xy wird hinzugefügt
